name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Export Java 8 toolchain
      run: |
        cat << "EOF" >> $HOME/.m2/toolchains.xml
        <toolchains>
          <toolchain>
            <type>jdk</type>
            <provides>
              <version>1.8</version>
              <vendor>adoptopenjdk</vendor>
              <id>for_mevenide</id>
            </provides>
            <configuration>
              <jdkHome>$JAVA_HOME</jdkHome>
            </configuration>
          </toolchain>
        </toolchains>
        EOF
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Build with Maven
      run: ./mvnw verify
